### ISSUE TITLE
Pypi linking to the wrong github repo

### ISSUE THREAD

**Issue by aianus** [4n4nd/prometheus-api-client-python#246]
Pypi still links to https://github.com/AICoE/prometheus-api-client-python

https://pypi.org/project/prometheus-api-client/ (Homepage link)

**Comment by 4n4nd** [comment]
This needs to be updated in the [setup.py](https://github.com/4n4nd/prometheus-api-client-python/blob/master/setup.py#L37). Thanks for letting us know 👍
