### ISSUE TITLE
Update https://pypi.org/project/prometheus-api-client/

### ISSUE THREAD

**Issue by sebastian-philipp** [4n4nd/prometheus-api-client-python#250]
Hi there, 

https://pypi.org/project/prometheus-api-client/ still points to the old location https://github.com/AICoE/prometheus-api-client-python which is an empty repository. 

Took me a while to figure out this project is still alive

**Comment by 4n4nd** [comment]
A new release should fix this issue ([required changes](https://github.com/4n4nd/prometheus-api-client-python/pull/248))

**Comment by 4n4nd** [comment]
A new release was created ([v0.5.2](https://github.com/4n4nd/prometheus-api-client-python/releases/tag/v0.5.2)) and this issue should be resolved now. Thanks for letting us know!
